workflows:
  android-release:
    name: Build Android Release (Play Store)
    
    # Máquina que vai compilar o código
    instance_type: mac_mini_m1 
    max_build_duration: 60
    
    environment:
      flutter: stable
      android_signing:
        - minha_chave_upload 

    scripts:
      - name: Criar key.properties no servidor do Codemagic
        script: |
          echo "storePassword=$CM_KEYSTORE_PASSWORD" >> android/key.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> android/key.properties
          echo "storeFile=$CM_KEYSTORE_PATH" >> android/key.properties
          
      - name: Baixar pacotes do Flutter
        script: |
          flutter pub get
          
      - name: Gerar App Bundle (Play Store) e APK (Testes)
        script: |
          # Gera o AAB para a Play Store já com o número incrementado automaticamente!
          flutter build appbundle --release --build-number=$BUILD_NUMBER
          
          # Gera o APK para você mandar pro celular também com o número atualizado!
          flutter build apk --release --build-number=$BUILD_NUMBER

    # Arquivos finais que o Codemagic vai te entregar para download no final do processo
    artifacts:
      - build/app/outputs/bundle/release/**/*.aab
      - build/app/outputs/flutter-apk/**/*.apk