name: towerrogue
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.23.0
  flame_audio: ^2.1.0
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.2.2
  flutter_soloud: ^3.4.10
  google_mobile_ads: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/sprites/
    - assets/images/sprites/inimigos/
    - assets/images/sprites/tileset/
    - assets/images/sprites/projeteis/
    - assets/images/sprites/hud/
    - assets/images/sprites/chars/
    - assets/images/sprites/itens/
    - assets/images/sprites/familiares/
    - assets/images/sprites/doorIcons/
    - assets/images/sprites/gameObjs/
    - assets/images/sprites/condicoes/
    - assets/audio/
    - assets/audio/music/
    - assets/audio/sfx/wav/
    - assets/audio/sfx/mp3/

  fonts:
    - family: pixelFont
      fonts:
        - asset: assets/fonts/pixel.ttf

  shaders:
    - shaders/crt.frag

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_ios.png" # O iOS vai usar esse (precisa ter fundo desenhado!)
  
  # ==========================================
  # CONFIGURAÇÃO ANDROID (Ícones Adaptativos)
  # ==========================================
  adaptive_icon_background: "#000000" # Um cinza bem escuro de masmorra
  adaptive_icon_foreground: "assets/images/icon.png"
  min_sdk_version: 21 
  web:
    generate: true
    image_path: "assets/images/icon.png"